apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tetris.fullname" . }}-config
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.environment | quote }}
  APP_VERSION: {{ .Values.appVersion | quote }}
