apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app

resources:
  - deployment.yaml
  - service.yaml
  - image-pull-secret.yaml

labels:
  - pairs:
      managed-by: argocd
      scenario: "04-harbor-argocd"
